import pandas as pd 
import numpy as np 
import matplotlib.pyplot 

Original_Data_Frame=pd.read_csv('DIABIMMUNE_WGS.WGS.sample_details.tsv', sep = '\t')

df=Original_Data_Frame.copy()

df.drop([   'Glutamic acid decarboxylase antibodies positive',
            'Age at first received rice (months)',
            'Subject ID',
            'Age at first received fish (months)',
            'Sex',
            'Age at first received milk products (months)',
            'Age at first received berries (months)',
            'Height-for-age z-score',
            'Host body product',
            'Host body site',
            'Age at first received apple (months)', 
            'Age at first received carrot (months)',
            'Age at height-for-age z-score measured (days)',
            'Child\'s diet first three days',
            'Age at first received egg (months)',
            'Yearly average weight gain during first three years (kg/year)',
            'Age at first received pear (months)',
            'Breastfed duration (days)',
            'Sample type',
            'Mom reported gestational diabetes',
            'data set',
            'Host body habitat',
            'Study group',
            'Type 1 diabetes diagnosed',
            'Host common name',
            'Age at first received poultry (months)',
            'Age at first received barley (months)',
            'Age at first received potato (months)',
            'Age at weight-for-age z-score measured (days)',
            'Malassezia restricta detected',
            'Maternal age at birth',
            'Exclusive breastfed duration (days)', 
            'Yearly average linear growth during first three years (cm/year)', 
            'Age at first received plum (months)', 
            'Age at BMI-for-age z-score measured (days)', 
            'Age at first received corn (months)', 
            'Age at first received sweet potato (months)', 
            'Age at first received wheat (months)', 
            'Age at first received solid food or non-human milk (months)', 
            'env_feature', 
            'Weight-for-height z-score', 
            'Delivery Mode', 
            'Urban or rural site', 
            'Linear growth during first year (cm)', 
            'BMI-for-age z-score', 
            'Age at first received cabbs (months)', 
            'HLA risk, by HLA haplotyping',
            'Age at first received tomato (months)',
            'Age at first received rye (months)',
            'Age at first received cowsmilk (months)',
            'Age at sample collection (months)',
            'Country', 
            'Age at first received oat (months)',
            'Age at first received peas (months)', 
            'Weight gain during first year (kg)',
            'Age at first received beef (months)',
            'Age at first received pork (months)',
            'Mom reported antibiotic use during pregnancy',
            'Age at first received banana (months)',
            'Age at diagnosis of type 1 diabetes', 
            'Matches for Blastocystis sp. subtype 2 (CPM)',
            'Matches for Penicillium (CPM)',
            'Matches for Saccharomyces cerevisiae (CPM)',
            'Matches for Candida albicans (CPM)',
            'Matches for Penicillium roqueforti (CPM)',
            'Matches for Wickerhamomyces (CPM)',
            'Matches for Candida parapsilosis (CPM)',	
            'Matches for Blastocystis (CPM)',
            'Matches for Torulaspora delbrueckii (CPM)',	
            'Matches for Wickerhamiella pararugosa (CPM)',
            'Matches for Penicillium sp. BW_MB (CPM)',	
            'Matches for Chaetomium globosum (CPM)',	
            'Matches for Rhodotorula (CPM)',	
            'Matches for Blastocystis sp. subtype 3 (CPM)',
            'Matches for Clavispora lusitaniae (CPM)',	
            'Matches for Meyerozyma guilliermondii (CPM)',	
            'Matches for Malassezia globosa (CPM)',	
            'Matches for Nakazawaea holstii (CPM)',	
            'Matches for Yarrowia lipolytica (CPM)',	
            'Matches for Blastocystis sp. subtype 4 (CPM)',	
            'Matches for [Candida] intermedia (CPM)',	
            'Matches for Cyberlindnera jadinii (CPM)',	
            'Matches for [Candida] inconspicua (CPM)',	
            'Matches for Meyerozyma sp. JA9 (CPM)',	
            'Matches for Lodderomyces elongisporus (CPM)',	
            'Matches for Aspergillus sp. MA 6041 (CPM)',	
            'Matches for Pichia membranifaciens (CPM)',	
            'Matches for Saccharomycetales (CPM)', 
            'Matches for Debaryomyces hansenii (CPM)',	
            'Matches for Metschnikowiaceae (CPM)',	
            'Matches for Blastocystis sp. subtype 1 (CPM)',	
            'Matches for Malassezia (CPM)',	
            'Matches for Meyerozyma caribbica (CPM)',	
            'Matches for Mycosphaerella populi (CPM)',	
            'Matches for Cryptosporidium meleagridis (CPM)',	
            'Matches for Hanseniaspora uvarum (CPM)',	
            'Matches for Kazachstania unispora (CPM)'], axis=1)




#for column in df.columns:$
#   print(column)


df.head()
print("run success")